[window]
opacity = 1
padding = { x = 15, y = 10 }

[colors.primary]
# background = "#18191a"
# foreground = "#cdcdcd
background = '#181616'
foreground = '#c5c9c5'

[keyboard]
bindings = [
    # { key = "d", mods = "Control", action = "None" }
]
