icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 50
warning_cpu = 70
critical_cpu = 90

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
# format = "$percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "packages"
package_manager = ["pacman"]
interval = 600
format = " 󰊠 updates available"
format_singular = " 󰊠 update available"
format_up_to_date = " 󰊠 up to date"
[[block.click]]
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
button = "left"
cmd = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-i3statusrs-$USER/ | rofi -dpi 1 -dmenu -config ~/.config/rofi/rofidmenu.rasi"
[[block.click]]
# Updates the block on right click
button = "right"
update = true

[[block]]
block = "time"
interval = 5
# format = " $timestamp.datetime(f:'%a %d/%m %R') "
